### PR TITLE
upgrade to joi 9.x.x

### PR DESCRIPTION
**Pull request by lancespeelmon**
FYI - this is blocking our upgrade to hapi 15.x. Thanks, L

```
> vision@4.1.0 test /private/tmp/vision
> lab -a code -t 100 -L



  ..................................................
  ..................................................
  ...................

119 tests complete
Test duration: 640 ms
Assertions count: 288 (verbosity: 2.42)
No global variable leaks detected
Coverage: 100.00%
Linting results: No issues
```

### CODE REVIEW

**Comment by Marsup** [comment]
How is that blocking ?

**Comment by lancespeelmon** [comment]
I am unable to shrinkwrap my project:
```
npm shrinkwrap --dev
npm WARN unmet dependency /Develop/trax/document-service/node_modules/vision requires joi@'8.x.x' but will load
npm WARN unmet dependency /Develop/trax/document-service/node_modules/joi,
npm WARN unmet dependency which is version 9.0.4
npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/lance/.nvm/versions/node/v4.5.0/bin/node" "/Users/lance/.nvm/versions/node/v4.5.0/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: joi@9.0.4 /Develop/trax/document-service/node_modules/joi
```
Am I missing something? Thanks! L

**Comment by Marsup** [comment]
I just did a quick shrinkwrap test, you should reinstall your deps, this not blocking at all.

**Comment by lancespeelmon** [comment]
Yes removing shrinkwrap and reinstalling depds worked. Thanks, L

**Pull request closed without merging**
