### PR TITLE
Report errors when loading helpers

### LINKED ISSUE #73: Send helper parsing error to user
If you include a helper in the helpers directory and it cannot be loaded (i.e. `require()` throws), [the error is lost](https://github.com/hapijs/vision/blob/master/lib/manager.js#L260). It would be useful to see some kind of error here, perhaps you just made a simple syntax error that needs fixing.

### PR DESCRIPTION
**Pull request by jagoda**
Fixes #73.

### CODE REVIEW

**Comment by jagoda** [comment]
@mtharrison @mugli this look like it meets your needs?

**Comment by mtharrison** [comment]
Having second thoughts about this, feels a bit wrong to me for a library to log to my stdout, even in warning situation. It could mess up whatever logging strategy I have in place. I wonder if there's a better way of doing this without throwing. Would it possible to use the hapi `request.log()`/`server.log()` here? Or at least use `console.error()` or `console.warn()` so it's sent to stderr.

Anyone else have a good idea?

**Comment by devinivy** [comment]
I personally think sending it to stderr is sufficient, and I agree that sending it to stdout feels bad.  I'm not convinced that hapi logging applies here very well.

**Comment by jagoda** [comment]
Thanks for the feedback! @mtharrison I considered `server.log()` but it seemed to run up against some of  your earlier concerns that the warning may not be immediately apparent in the default case. This is because logging would have to be explicitly configured on the server (either via a plugin or the `debug` option) in order to see the output. Also, since this issue seems to skew toward the development cycle I don't think that a whole lot is lost by not sending the warning to `server.log()`. However, I had not considered how stdout could mess up other logging strategies. `console.warn()` seems reasonable to me. I will update accordingly if nobody can think of any final objections.

**Pull request merged**
