### PR TITLE
updated marko example 

### PR DESCRIPTION
**Pull request by csakis**
William!
I updated the marko example with a more complicated example to show MarkoJS advantages.
I added a 
- layout
- include (footer)
-  custom component.

### CODE REVIEW

**Comment by csakis** [comment]
Let me try to fix the problems first

**Comment by wswoodruff** [comment]
Hey @csakis Thanks so much for updating the example! You should be able to run it locally if you clone vision, run npm install and run `node examples/marko`. It's ok to keep the PR open while you fix those minor lint changes =)

**Comment by csakis** [comment]
I am kinda new to pull requests and am not really confident how I should do it. I have just read the contributor's guide and it said that I should do PR only on the master branch

**Comment by wswoodruff** [comment]
Oh! You're right! Good stuff thanks for reading that!!

**Pull request closed without merging**
