### PR TITLE
Add .npmignore

### LINKED ISSUE #150: Add `.npmignore`
I noticed you are shipping various redundant files to npm, such as tests, examples, build configs and documents.

Omitting those should reduce the package size to roughly 10%.

### PR DESCRIPTION
**Pull request by SimonSchick**
Quick and easy.

Package size:
before: `28578`
after: `7954`
which is about 73% smaller!

Closes #150

### CODE REVIEW

**Comment by Marsup** [comment]
We have a standard .npmignore in many other projects, you might want to look at that and eventually adapt.

**Comment by SimonSchick** [comment]
Ah yes, I wasn't sure if you like the inverted glob style, some people consider this hacky 😛

**Comment by Marsup** [comment]
Would be better to squash the commits to avoid having the tgz in the tree, otherwise it's :+1:

**Comment by SimonSchick** [comment]
@Marsup you should have the option to squash merge yourself, unless that doesn't work with 3rd party pull requests.

**Comment by Marsup** [comment]
Indeed, I just don't like how github does that, I'll let @wswoodruff decide :)

**Comment by SimonSchick** [comment]
@Marsup did it regardless.

Also I'm curious, what do you not like about it? The fact that it doesn't create a merge commit and/or the fact that it doesn't persist signing etc.?

**Comment by Marsup** [comment]
The lack of merge commit indeed.

**Comment by wswoodruff** [comment]
Dang I missed the context of the merge squashing cuz history has been changed!! loLL

**Comment by wswoodruff** [comment]
Looks good -- thx for raising and solving the issue @SimonSchick!

**Comment by SimonSchick** [comment]
Any eta on a release @wswoodruff ?

**Comment by wswoodruff** [comment]
Yup workin on it now

**Comment by wswoodruff** [comment]
@SimonSchick `v5.3.3` released! Thanks 👍

**Pull request merged**
