### PR TITLE
Handle ESM for helpers

### LINKED ISSUE #145: Should handle helpers as ES Module
As of today vision only support helpers defined as a CJS module as a function

```
module.exports = function() {
  // ...
}
```

Supporting ESM and even more, named export would be a great step forward.

```
export function myHelper() {
  // ...
}
```

### PR DESCRIPTION
**Pull request by JSteunou**
named export first, then default, then CJS

should resolve #145

### CODE REVIEW

**Comment by wswoodruff** [comment]
Hi @JSteunou! Thanks for your contribution! Can you please add tests to cover those line changes to keep code coverage at 100%?

**Comment by JSteunou** [comment]
Sure but I might need some help for that

**Comment by wswoodruff** [comment]
@JSteunou Change one of these helpers to ESM and run `npm test` to make sure the code coverage goes to 100% https://github.com/hapijs/vision/tree/master/test/templates/valid/helpers

**Comment by wswoodruff** [comment]
I was torn between adding a new test just for this feature or changing one of the existing helpers to ESM but it's really not worth a new test I think, unless someone else who works on this module thinks otherwise

**Comment by devinivy** [comment]
How will you hit full code coverage without a new test (or two)?

**Comment by wswoodruff** [comment]
All the helpers are being used and are CommonJS modules -- the new changes should be covered if one of them is changed to ESM

**Comment by devinivy** [comment]
Ah, I see what you mean.  There are a few cases here to hit,
```js
const helper = required[name] || required.default || required;
```

**Comment by wswoodruff** [comment]
Oh yeah! Forgot about `.default` =P
@JSteunou In order to hit 100% code coverage can you please add a dedicated test for ESM helpers?
You can use this test as a starting point to copy / paste / modify
https://github.com/hapijs/vision/blob/master/test/index.js#L589-L605

The helpers can do whatever you like, they can even just be copies of 'long' and 'uppercase', but exposed as ESM modules.

We'll need to cover the cases where one is exported as default, and the other is a named export

Checklist:
- 2 new ESM helpers in https://github.com/hapijs/vision/tree/master/test/templates/valid/helpers
    - One exports as default
    - One is a named export
- New test to cover both of these similar to https://github.com/hapijs/vision/blob/master/test/index.js#L589-L605

**Comment by JSteunou** [comment]
Sure, thanks for the hints, I'll try this asap

**Comment by JSteunou** [comment]
Ok I had to simulate ESModule behavior with CJS exports because I couldn't update the all test suite, but that should be enough :)

**Comment by wswoodruff** [comment]
Hmmm I'm asking myself why are these weird global leaks happening all of a sudden causing tests to fail? `The following leaks were detected:__core-js_shared__`

This line in `hapi-react-views` seems to mitigate this issue by ignoring it on the lab test call, I don't know why it's happening rn tho.. https://github.com/jedireza/hapi-react-views/blob/master/package.json#L7

**Comment by JSteunou** [comment]
New node 8.10 or related to what I added?

**Comment by wswoodruff** [comment]
The only other issue I have is the tests aren't using ESM -- but I'm still considering merging it

**Comment by JSteunou** [comment]
If you have a solution to use true ESM inside test I will take it ;)

**Comment by wswoodruff** [comment]
After poking around, ESM in a test without babel looks like a nightmare -- no need to add anything more.

Thank you so much @JSteunou for your contribution!!

**Pull request merged**
